import { colors, fontFamily } from "@/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 32,
    paddingVertical: 20,
    flex: 1,
  },
  header: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    zIndex: 1,
  },
  headerTitle: {
    color: colors.gray100,
    fontSize: 16,
    fontFamily: fontFamily.semiBold,
    fontWeight: "bold",
  },
  formContainer: {
    marginTop: 28,
    marginBottom: 28,
    zIndex: 1,
  },
  input: {
    color: colors.gray200,
    fontSize: 16,
    height: 50,
    backgroundColor: colors.gray800,
    marginVertical: 4,
    borderRadius: 6,
    paddingLeft: 16,
    borderWidth: 1,
    borderColor: colors.gray600,
  },
  currencyContainer: {
    flexDirection: "row",
    alignItems: "center",
    color: colors.gray200,
    backgroundColor: colors.gray800,
    borderWidth: 1,
    borderColor: colors.gray600,
    borderRadius: 6,
    height: 50,
    marginVertical: 8,
    paddingHorizontal: 16,
    gap: 4,
  },
  currencyPrefix: {
    color: colors.gray200,
    fontSize: 16,
    fontWeight: "500",
  },
  currencyInputControl: {
    flex: 1,
    color: colors.gray400,
    fontSize: 16,
    height: "100%",
  },
  participantsButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.gray800,
    borderWidth: 1,
    borderColor: colors.gray600,
    borderRadius: 8,
    padding: 16,
    marginTop: 4,
    gap: 12,
  },
  participantsButtonText: {
    color: colors.gray400,
    fontSize: 16,
  },
  selectedList: {
    marginTop: 16,
  },
  participantRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.gray700,
    paddingHorizontal: 0,
    paddingVertical: 12,
    gap: 12,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 100,
    backgroundColor: colors.gray600,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    color: colors.gray200,
    fontFamily: fontFamily.bold,
    fontSize: 12,
  },
  participantName: {
    flex: 1,
    color: colors.gray200,
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
  },
  dropdownMenu: {
    position: "absolute",
    left: 0,
    right: 0,
    backgroundColor: colors.gray700,
    elevation: 5,
    maxHeight: 200,
    zIndex: 99,
  },
  dropdownScroll: {
    padding: 12,
  },
  dropdownRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
  },
  footer: {
    marginVertical: 24,
  },
});
